version: '3.8'

services:
  # Python爬虫服务
  lottery-crawler:
    build:
      context: ./python-crawler
      dockerfile: Dockerfile
    container_name: lottery-python-crawler
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # 数据库配置
      - DB_HOST=192.168.1.34
      - DB_PORT=3306
      - DB_USER=lbc
      - DB_PASSWORD=19940314
      - DB_NAME=luck_money
      # 爬虫配置
      - CRAWLER_ENV=docker
      - LOG_LEVEL=INFO
    volumes:
      # 日志目录挂载
      - ./python-crawler/logs:/app/logs
      # 图表输出目录挂载
      - ./python-crawler/charts:/app/charts
      # 配置文件挂载（可选，用于动态配置）
      - ./python-crawler/config.py:/app/config.py:ro
    networks:
      - lottery-network
    depends_on:
      - mysql-check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MySQL连接检查服务
  mysql-check:
    image: mysql:8.0
    container_name: lottery-mysql-check
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=temp
    command: >
      sh -c "
        echo '等待MySQL服务就绪...' &&
        until mysql -h 192.168.1.34 -P 3306 -u lbc -p19940314 -e 'SELECT 1'; do
          echo 'MySQL未就绪，等待5秒...' &&
          sleep 5
        done &&
        echo 'MySQL连接成功！'
      "
    networks:
      - lottery-network

networks:
  lottery-network:
    driver: bridge
